// Startup data for the game
export interface StartupData {
  name: string;
  category: string;
  founded: number; // Actual founding year
  r: number; // Annual r in billions USD
  timeToUnicorn: number; // Years to reach unicorn status (e.g., 7.5 = 7 years 6 months)
  valuation: number; // Valuation in billions USD
  power: number; // Changed from revenue
}

export const startupData: StartupData[] = [
  {
    name: "Elevenlabs",
    category: "AI Voice",
    founded: 2022,
    r: 0,
    timeToUnicorn: 2,
    valuation: 1,
    power: 8,
  },
  {
    name: "Runway",
    category: "AI Video",
    founded: 2018,
    r: 0,
    timeToUnicorn: 5,
    valuation: 1.5,
    power: 7,
  },
  {
    name: "Replit",
    category: "Coding",
    founded: 2016,
    r: 0,
    timeToUnicorn: 6,
    valuation: 1.2,
    power: 8,
  },
  {
    name: "Anthropic",
    category: "AI Research",
    founded: 2021,
    r: 0,
    timeToUnicorn: 2,
    valuation: 5,
    power: 9,
  },
  {
    name: "Vercel",
    category: "Web Hosting",
    founded: 2015,
    r: 0,
    timeToUnicorn: 5,
    valuation: 2.5,
    power: 7,
  },
  {
    name: "Cloudflare",
    category: "Security",
    founded: 2009,
    r: 1,
    timeToUnicorn: 7,
    valuation: 20,
    power: 9,
  },
  {
    name: "Indrive",
    category: "Ride Hailing",
    founded: 2013,
    r: 0,
    timeToUnicorn: 6,
    valuation: 1,
    power: 7,
  },
  {
    name: "Calendly",
    category: "Scheduling",
    founded: 2013,
    r: 0,
    timeToUnicorn: 7,
    valuation: 3,
    power: 8,
  },
  {
    name: "Clubhouse",
    category: "Social Audio",
    founded: 2020,
    r: 0,
    timeToUnicorn: 1,
    valuation: 4,
    power: 6,
  },
  {
    name: "Quora",
    category: "Q&A",
    founded: 2009,
    r: 0,
    timeToUnicorn: 8,
    valuation: 2,
    power: 7,
  },
  {
    name: "Robinhood",
    category: "Trading",
    founded: 2013,
    r: 0,
    timeToUnicorn: 5,
    valuation: 10,
    power: 8,
  },
  {
    name: "Coinbase",
    category: "Crypto",
    founded: 2012,
    r: 0,
    timeToUnicorn: 6,
    valuation: 80,
    power: 9,
  },
  {
    name: "Lyft",
    category: "Ride Sharing",
    founded: 2012,
    r: 0,
    timeToUnicorn: 5,
    valuation: 15,
    power: 8,
  },
  {
    name: "GitHub",
    category: "Development",
    founded: 2008,
    r: 0,
    timeToUnicorn: 6,
    valuation: 7.5,
    power: 9,
  },
  {
    name: "Stripe",
    category: "Payments",
    founded: 2010,
    r: 0,
    timeToUnicorn: 4,
    valuation: 50,
    power: 9,
  },
  {
    name: "OpenAI",
    category: "AI Research",
    founded: 2015,
    r: 0,
    timeToUnicorn: 4,
    valuation: 90,
    power: 10,
  },
];
