// Startup data for the game
export const startupData = [
  {
    name: "Zerodha",
    category: "Fintech",
    innovation: 8,
    growth: 9,
    userBase: 9,
    valuation: 8,
  },
  {
    name: "CRED",
    category: "Fintech",
    innovation: 9,
    growth: 8,
    userBase: 7,
    valuation: 9,
  },
  {
    name: "Razorpay",
    category: "Fintech",
    innovation: 8,
    growth: 9,
    userBase: 8,
    valuation: 8,
  },
  {
    name: "Zoho",
    category: "SaaS",
    innovation: 7,
    growth: 8,
    userBase: 9,
    valuation: 8,
  },
  {
    name: "Freshworks",
    category: "SaaS",
    innovation: 8,
    growth: 7,
    userBase: 8,
    valuation: 9,
  },
  {
    name: "Zomato",
    category: "Consumer",
    innovation: 7,
    growth: 9,
    userBase: 10,
    valuation: 8,
  },
  {
    name: "Swiggy",
    category: "Consumer",
    innovation: 8,
    growth: 9,
    userBase: 9,
    valuation: 8,
  },
  {
    name: "Byju's",
    category: "EdTech",
    innovation: 8,
    growth: 10,
    userBase: 9,
    valuation: 10,
  },
  {
    name: "Ola",
    category: "Consumer",
    innovation: 7,
    growth: 8,
    userBase: 9,
    valuation: 8,
  },
  {
    name: "Paytm",
    category: "Fintech",
    innovation: 8,
    growth: 9,
    userBase: 10,
    valuation: 9,
  },
  {
    name: "Flipkart",
    category: "Consumer",
    innovation: 7,
    growth: 8,
    userBase: 10,
    valuation: 10,
  },
  {
    name: "Meesho",
    category: "Consumer",
    innovation: 8,
    growth: 9,
    userBase: 8,
    valuation: 7,
  },
  {
    name: "PhonePe",
    category: "Fintech",
    innovation: 8,
    growth: 9,
    userBase: 9,
    valuation: 8,
  },
  {
    name: "Lenskart",
    category: "Consumer",
    innovation: 7,
    growth: 8,
    userBase: 7,
    valuation: 7,
  },
  {
    name: "Postman",
    category: "SaaS",
    innovation: 9,
    growth: 8,
    userBase: 8,
    valuation: 8,
  },
  {
    name: "Unacademy",
    category: "EdTech",
    innovation: 8,
    growth: 9,
    userBase: 8,
    valuation: 8,
  },
  {
    name: "ShareChat",
    category: "Social Media",
    innovation: 8,
    growth: 9,
    userBase: 9,
    valuation: 7,
  },
  {
    name: "Delhivery",
    category: "Logistics",
    innovation: 7,
    growth: 8,
    userBase: 8,
    valuation: 9,
  },
  {
    name: "Groww",
    category: "Fintech",
    innovation: 8,
    growth: 9,
    userBase: 8,
    valuation: 7,
  },
  {
    name: "upGrad",
    category: "EdTech",
    innovation: 7,
    growth: 8,
    userBase: 7,
    valuation: 7,
  },
  {
    name: "CarDekho",
    category: "Automotive",
    innovation: 7,
    growth: 8,
    userBase: 8,
    valuation: 7,
  },
  {
    name: "Dunzo",
    category: "Consumer",
    innovation: 8,
    growth: 7,
    userBase: 8,
    valuation: 6,
  },
  {
    name: "CoinDCX",
    category: "Crypto",
    innovation: 8,
    growth: 7,
    userBase: 7,
    valuation: 7,
  },
  {
    name: "Urban Company",
    category: "Consumer",
    innovation: 8,
    growth: 8,
    userBase: 8,
    valuation: 7,
  },
];
