// Startup data for the game
export interface StartupData {
  name: string;
  category: string;
  founded: number; // Actual founding year
  revenue: number; // Annual revenue in billions USD
  timeToUnicorn: number; // Years to reach unicorn status (e.g., 7.5 = 7 years 6 months)
  valuation: number; // Valuation in billions USD
}

export const startupData: StartupData[] = [
  {
    name: "Zerodha",
    category: "Fintech",
    founded: 2010,
    revenue: 1.1,
    timeToUnicorn: 10.2,
    valuation: 2.0,
  },
  {
    name: "CRED",
    category: "Fintech",
    founded: 2018,
    revenue: 0.4,
    timeToUnicorn: 2.8,
    valuation: 6.4,
  },
  {
    name: "Razorpay",
    category: "Fintech",
    founded: 2014,
    revenue: 0.75,
    timeToUnicorn: 6.3,
    valuation: 7.5,
  },
  {
    name: "Zoho",
    category: "SaaS",
    founded: 1996,
    revenue: 1.1,
    timeToUnicorn: 21.4,
    valuation: 5.0,
  },
  {
    name: "Freshworks",
    category: "SaaS",
    founded: 2010,
    revenue: 0.48,
    timeToUnicorn: 8.6,
    valuation: 3.5,
  },
  {
    name: "Zomato",
    category: "Consumer",
    founded: 2008,
    revenue: 1.8,
    timeToUnicorn: 12.1,
    valuation: 5.4,
  },
  {
    name: "Swiggy",
    category: "Consumer",
    founded: 2014,
    revenue: 1.3,
    timeToUnicorn: 3.9,
    valuation: 10.7,
  },
  {
    name: "Byju's",
    category: "EdTech",
    founded: 2011,
    revenue: 2.8,
    timeToUnicorn: 7.2,
    valuation: 22.0,
  },
  {
    name: "Ola",
    category: "Consumer",
    founded: 2010,
    revenue: 1.1,
    timeToUnicorn: 4.8,
    valuation: 7.3,
  },
  {
    name: "Paytm",
    category: "Fintech",
    founded: 2010,
    revenue: 2.5,
    timeToUnicorn: 5.7,
    valuation: 16.0,
  },
  {
    name: "Flipkart",
    category: "Consumer",
    founded: 2007,
    revenue: 5.7,
    timeToUnicorn: 5.3,
    valuation: 37.6,
  },
  {
    name: "Meesho",
    category: "Consumer",
    founded: 2015,
    revenue: 0.8,
    timeToUnicorn: 5.9,
    valuation: 4.9,
  },
  {
    name: "PhonePe",
    category: "Fintech",
    founded: 2015,
    revenue: 2.1,
    timeToUnicorn: 5.4,
    valuation: 12.0,
  },
  {
    name: "Lenskart",
    category: "Consumer",
    founded: 2010,
    revenue: 0.46,
    timeToUnicorn: 9.8,
    valuation: 4.5,
  },
  {
    name: "Postman",
    category: "SaaS",
    founded: 2014,
    revenue: 0.3,
    timeToUnicorn: 6.4,
    valuation: 5.6,
  },
  {
    name: "Unacademy",
    category: "EdTech",
    founded: 2015,
    revenue: 0.85,
    timeToUnicorn: 5.3,
    valuation: 3.4,
  },
  {
    name: "ShareChat",
    category: "Social Media",
    founded: 2015,
    revenue: 0.25,
    timeToUnicorn: 6.2,
    valuation: 5.0,
  },
  {
    name: "Delhivery",
    category: "Logistics",
    founded: 2011,
    revenue: 1.6,
    timeToUnicorn: 8.4,
    valuation: 4.2,
  },
  {
    name: "Groww",
    category: "Fintech",
    founded: 2016,
    revenue: 0.35,
    timeToUnicorn: 4.8,
    valuation: 3.0,
  },
  {
    name: "upGrad",
    category: "EdTech",
    founded: 2015,
    revenue: 0.32,
    timeToUnicorn: 6.3,
    valuation: 2.25,
  },
  {
    name: "CarDekho",
    category: "Automotive",
    founded: 2008,
    revenue: 0.45,
    timeToUnicorn: 13.2,
    valuation: 1.2,
  },
  {
    name: "Dunzo",
    category: "Consumer",
    founded: 2014,
    revenue: 0.2,
    timeToUnicorn: 7.1,
    valuation: 0.8,
  },
  {
    name: "CoinDCX",
    category: "Crypto",
    founded: 2018,
    revenue: 0.28,
    timeToUnicorn: 3.2,
    valuation: 2.15,
  },
  {
    name: "Urban Company",
    category: "Consumer",
    founded: 2014,
    revenue: 0.32,
    timeToUnicorn: 7.4,
    valuation: 2.8,
  },
];
